env:
  browser: true
  es2020: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 11
rules:
  no-unused-vars: ["error", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }]
  prefer-const: ["error"]
 


